import js from "@eslint/js";
import tseslint from "typescript-eslint";
import globals from "globals";

export default tseslint.config(
  {
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/.next/**",
      "**/coverage/**",
      "**/generated/**",
      // CDK synth output. Generated by `cdk synth`/`cdk deploy`, contains bundled
      // Lambda assets for custom resources, and is regenerated on every synth.
      "**/cdk.out/**",
      // Generated by `next build`; Next.js regenerates it and marks it do-not-edit.
      "**/next-env.d.ts",
      // Vendored by the AgentCore CLI (agentcore create / deploy regenerates it).
      // Not ours to lint, and it is overwritten on CLI upgrade.
      "agents/*/agentcore/cdk/**",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.strict,
  {
    languageOptions: {
      globals: {
        ...globals.node,
      },
    },
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/consistent-type-imports": "error",
    },
  },
);
