-- =====================================================================
-- MOVED — this file is no longer the canonical schema.
--
-- As of Story S-102 (issue #115) the schema is a Supabase CLI migration.
-- The canonical, executed source of truth is now:
--
--     supabase/migrations/20260902200101_initial_schema.sql
--
-- This stub is kept only so existing Markdown links to
-- `docs/reference/001_schema.sql` still resolve. Do NOT add DDL here — it
-- would drift from the migration and never be applied. Edit the migration
-- (or add a new timestamped migration) instead.
-- =====================================================================
