-- =====================================================================
-- MOVED — this file is no longer the canonical seed.
--
-- As of Story S-102 (issue #115) the seed is applied by the Supabase CLI
-- during `supabase db reset`. The canonical, executed source of truth is now:
--
--     supabase/seed.sql
--
-- This stub is kept only so existing Markdown links to
-- `docs/reference/002_seed.sql` still resolve. Do NOT add seed SQL here — it
-- would drift from supabase/seed.sql and never be applied. Edit
-- `supabase/seed.sql` instead.
-- =====================================================================
